version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "webhook-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nwx9ueizf9r0"
s3_prefix = "webhook-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "MyWebhookURL=\"https://webhook.site/c7b0dc81-5b73-46cd-b076-2be687ef6c79\""
image_repositories = []
